export const TODOS_ADD_TODO_LIST = 'TODOS_ADD_TODO_LIST';
export const TODOS_ADD_TODO_LIST_SUCCESS = 'TODOS_ADD_TODO_LIST_SUCCESS';
export const TODOS_ADD_TODO_LIST_FAILED = 'TODOS_ADD_TODO_LIST_FAILED';
